Guias usadas:
- Creación, conexión con cliente Supabase y extracción de data https://supabase.com/docs/reference/python/initializing

Librerias

In [19]:
import sys
sys.executable

'c:\\Users\\Angelica\\Documents\\Temporal-Carrera\\PerceivoAI\\REPOS_GITHUB\\.venv\\Scripts\\python.exe'

In [82]:
import os
from dotenv import load_dotenv
import pandas as pd
import requests
from requests.auth import HTTPBasicAuth
from tqdm import tqdm
from pathlib import Path
import numpy as np

## Extract

In [6]:
def obtener_datos(endpoint, login, authtoken):
    # Asegurar que la carpeta exista
    Path("data/raw").mkdir(parents=True, exist_ok=True)


    datos = []
    page = 1
    barra= tqdm(desc=f"Descargando '{endpoint}'", unit=" páginas")

    while (True):
        url = f"https://api.jumpseller.com/v1/{endpoint}.json?page={page}&limit=50"
        r = requests.get(url, auth=HTTPBasicAuth(login, authtoken))
        if r.status_code != 200:
            print(f"❌ Error al obtener {endpoint}:", r.status_code)
            break

        data = r.json()
        if not data:
            break

        datos.extend(data)
        barra.update(1) # avanza la barra en 1 unidad
        page += 1

    barra.close()


    print(f"✅ Data obtenida: {endpoint.title()}. Total páginas {page-1}\n")
    datos= pd.json_normalize(datos)
    return datos

# datos.to_parquet(f"data/raw/{endpoint}_raw.parquet", index=False) # se almacena la data raw
    # datos.to_csv(f"data/raw/{endpoint}_raw.csv", index=False)

Probar que si se carga un archivo a **supabase**
- Guia oficial(click en Connect y seleccionar el proyecto para obtener las credenciales): 
  - https://supabase.com/dashboard/project/mbzsgavapsezblkypfwi?showConnect=true
  - https://supabase.com/docs/guides/troubleshooting/using-sqlalchemy-with-supabase-FUqebT
  
- pip install python-dotenv sqlalchemy psycopg2

In [7]:
def to_serializable(obj):
    if isinstance(obj, np.ndarray):
        return [to_serializable(x) for x in obj.tolist()]
    elif isinstance(obj, dict):
        return {k: to_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [to_serializable(x) for x in obj]
    else:
        return obj  # valores simples

# Ejemplo aplicado al df
# df["col_limpia"] = df["col_original"].apply(
#     lambda fila: json.dumps(to_serializable(fila))
# )

In [8]:
# para evitar problema como: can't adapt type 'numpy.ndarray'
# serializamos los valores array a str
import json
def preprocessing_supabase(data_extracted):
    
    col_to_serializar=[]
    for col in data_extracted.columns:
        if data_extracted[col].apply(lambda x: isinstance(x, (np.ndarray, dict, list))).any(): 
            col_to_serializar.append(col)
    # ['product.categories', 'product.images', 'product.variants', 'product.fields]

    # print(col_to_serializar)
    if col_to_serializar: # si hay columnas 
        for col in col_to_serializar:
            # data_extracted[col]=data_extracted[col].apply(lambda fila: json.dumps(fila.tolist()) if isinstance(fila, np.ndarray) else json.dumps(fila))

            data_extracted[col] = data_extracted[col].apply( lambda fila: json.dumps(to_serializable(fila)) )
            
        print(f'Dataframe serializado. \nColumnas Serializadas: {col_to_serializar}\n')
    else:
        print('Nada que serializar')
    # return data_extracted

In [ ]:
products_df= pd.read_parquet("data/raw/products_raw.parquet")
customers_df= pd.read_parquet("data/raw/customers_raw.parquet")
orders_df= pd.read_parquet("data/raw/orders_raw.parquet")
# data/raw/{endpoint}_raw.parquet

## Supabase
Conexion con el proyecto en supabase

In [9]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

# Load environment variables from .env
load_dotenv()

def conect2supabase():
    # Fetch variables
    USER = os.getenv("user")
    PASSWORD = os.getenv("password")
    HOST = os.getenv("host")
    PORT = os.getenv("port")
    DBNAME = os.getenv("dbname")

    # Construct the SQLAlchemy connection string
    DATABASE_URL = f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}?sslmode=require"

    # Create the SQLAlchemy engine
    engine = create_engine(DATABASE_URL)
    print('✅ Supabase: Conexión Exitosa')
    return engine
    # # Test the connection
    # try:
    #     with engine.connect() as connection:
    #         print("Connection successful!")
    # except Exception as e:
    #     print(f"Failed to connect: {e}")

Insertamos archivo de prueba

In [11]:
# hago el cambio a csv
# products_csv= products_df.

# endpoint= 'products'
# esquema= 'raw'
def insert2supabase(engine,esquema, endpoint, df):
    try: 
        table_name= f'{endpoint}_raw'
        df.to_sql(
            table_name,
            con=engine,
            schema=esquema, # el esquema debe estar creado previamente
            if_exists='append', #append para no soreescribir
            index=False
        )
        print(f'💾 Creación exitosa de la tabla {table_name} en el esquema {esquema}.\n')
    except Exception as e:
        print(f"Error para crear la tabla {table_name}: {e}")

In [29]:
endpoint='customers'
id_name= f"{endpoint[:-1]}.id"
id_name

'customer.id'

In [39]:
import pandas as pd
from sqlalchemy import inspect

def insert2supabase(engine, esquema, endpoint, df):
    table_name = f"{endpoint}_raw"
    full_table_name = f"{esquema}.{table_name}"

    try:
        inspector = inspect(engine)

        # 1️⃣ Verificar si la tabla ya existe en el esquema
        table_exists = inspector.has_table(table_name, schema=esquema)

        if not table_exists:
            # Crear tabla desde cero
            df.to_sql(
                table_name,
                con=engine,
                schema=esquema,
                if_exists="replace",  # replace crea la tabla si no existe
                index=False
            )
            print(f"💾 Tabla {full_table_name} creada con {len(df)} filas.")
            return

        # 2️⃣ Si la tabla ya existe, traer IDs existentes
        id_name= f"{endpoint[:-1]}.id" # tengo que limpiar la ultima letra
    
        with engine.connect() as conn:
            query = f'SELECT "{id_name}" FROM {full_table_name}'
            existing_ids = pd.read_sql( query, conn )[id_name].tolist()

        # 3️⃣ Filtrar solo las filas nuevas
        df_new = df[~df[id_name].isin(existing_ids)]

        if not df_new.empty:
            df_new.to_sql(
                table_name,
                con=engine,
                schema=esquema,
                if_exists="append",
                index=False
            )
            print(f"💾 {len(df_new)} nuevas filas insertadas en {full_table_name}.")
        else:
            print(f"ℹ️ No hay nuevas filas para insertar en {full_table_name}.")

    except Exception as e:
        print(f"❌ Error insertando en {full_table_name}: {e}")

Ejecución

In [12]:
load_dotenv()

login =  os.getenv('JUMPSELLER_LOGIN')
authtoken =  os.getenv('JUMPSELLER_AUTHTOKEN')

endpoints=[ "products","customers","orders"]

dataframes={}
for endpoint in endpoints:
    dataframes[f'df_{endpoint}']= obtener_datos(endpoint, login, authtoken)

Descargando 'products': 24 páginas [00:37,  1.56s/ páginas]

✅ Data obtenida: Products. Total páginas 24

Descargando 'customers': 33 páginas [00:20,  1.58 páginas/s]

✅ Data obtenida: Customers. Total páginas 33

Descargando 'orders': 34 páginas [00:32,  1.04 páginas/s]

✅ Data obtenida: Orders. Total páginas 34

In [14]:
dataframes.keys()

dict_keys(['df_products', 'df_customers', 'df_orders'])

In [15]:
for key, df in dataframes.items():
    print(key)
    preprocessing_supabase(df)

df_products
Dataframe serializado.
Columnas Serializadas: ['product.categories', 'product.images', 'product.variants', 'product.fields']

df_customers
Dataframe serializado.
Columnas Serializadas: ['customer.shipping_addresses', 'customer.billing_addresses', 'customer.customer_categories', 'customer.customer_additional_fields']

df_orders
Dataframe serializado.
Columnas Serializadas: ['order.promotions', 'order.products', 'order.additional_fields', 'order.shipping_taxes']

In [16]:
engine_supabase= conect2supabase()

✅ Supabase: Conexión Exitosa

In [40]:
esquema= 'raw'

# endpoint= ['products','orders','customers']
for key, df in tqdm(dataframes.items(), desc= 'Insertando en Supabase'):
    for endpoint in endpoints:
        if key.endswith(endpoint):
            insert2supabase(engine_supabase,esquema, endpoint, df)

Insertando en Supabase:  33%|███▎      | 1/3 [02:15<04:31, 135.76s/it]

💾 Tabla raw.products_raw creada con 1198 filas.

Insertando en Supabase:  67%|██████▋   | 2/3 [02:18<00:57, 57.42s/it]

💾 Tabla raw.customers_raw creada con 1617 filas.

Insertando en Supabase: 100%|██████████| 3/3 [02:26<00:00, 48.81s/it]

💾 Tabla raw.orders_raw creada con 1679 filas.

In [ ]:
# insertando nuevamente
insert2supabase(engine_supabase,esquema, 'customers', dataframes['df_customers'])

ℹ️ No hay nuevas filas para insertar en raw.customers_raw.

## Transform

Siguiente paso: extraer los datos raw de Supabase

**Consideraciones** en Supabase <p>
- Crear vistas en public para que apunten a las tablas en el esquema 'raw'.(sql editor)
```
CREATE VIEW public.customers_raw as
SELECT * FROM raw.customers_raw;

CREATE VIEW public.products_raw as
SELECT * FROM raw.products_raw;

CREATE VIEW public.orders_raw as
SELECT * FROM raw.orders_raw;
```

- Generación de Columnas de products_raw sin categorias. Se copia el resultado en un string.
```
SELECT string_agg('"' || column_name || '"', ' , ')
FROM information_schema.columns
WHERE table_schema = 'raw'
  AND table_name   = 'products_raw'
  AND column_name <> 'product.categories';
  ```
- Configurar número máximo de filas que retorna por proyecto o usar paginación para traer por lotes(2da opción usada).

### FUNCIONES

1. **Extracción** de data_raw en supabase

In [5]:
import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()
url= os.environ.get("SUPABASE_URL")
key= os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

In [ ]:
# extrae todos los endpoints, ya no es necesario realizar el for fuera de la funcion

# Traer la información por lotes
# consideración hasta 5000 mil registros
    
def extract_supabase_raw(endpoint): # cambiar despues a endpoints(lista)
    name_table= f"{endpoint}_raw"
    rango= [0,1000,2000,3000,4000]
    # evaluar o almacenar mientras exista rango en la tabla si lanza el error entonces parar

    parts_table=[]

    if endpoint=='products': # columnas obtenidas luego de query en SQL EDITOR
        products_column=' "product.id" , "product.name" , "product.page_title" , "product.description" , "product.meta_description" , "product.price" , "product.cost_per_item" , "product.compare_at_price" , "product.weight" , "product.stock" , "product.stock_unlimited" , "product.stock_threshold" , "product.stock_notification" , "product.sku" , "product.brand" , "product.barcode" , "product.featured" , "product.reviews_enabled" , "product.status" , "product.shipping_required" , "product.type" , "product.days_to_expire" , "product.created_at" , "product.updated_at" , "product.package_format" , "product.length" , "product.width" , "product.height" , "product.diameter" , "product.google_product_category" , "product.images" , "product.variants" , "product.fields" , "product.permalink" , "product.discount" , "product.currency" '
        select_query=products_column
    else:
        select_query="*"

    # Obtener data de Supabase por partes
    for ind, valor in enumerate(rango):
        table_chunk = ( 
        supabase.table(name_table)
        .select(select_query)
        .range(valor,valor+999) # 0,999 , lo mismo= rango[ind]
        .execute()
            )
        if len(table_chunk.data): # si existe la tabla en ese rango
            parts_table.append(table_chunk.data)
        else:
            break

    completed_table =[]

    # Juntar todas las listas en una sola lista
    for i in range(len(parts_table)):
        completed_table+= parts_table[i]
    
    print(f'✅ Extracción correcta realizada para {name_table}')
    print(f"Filas: {len(completed_table)}\n")

    return pd.DataFrame(completed_table)

2. Definir funciones de transformacion para cada tabla

### FLUJO DE EJECUCIÓN

In [53]:
endpoints

['products', 'customers', 'orders']

1. Ejecución de extracción(data_raw)

In [ ]:
# endpoints
# customers_raw=extract_supabase_raw(endpoint='customers')
# products_raw= extract_supabase_raw('products')
# orders_raw= extract_supabase_raw('orders')
df_raw= {}
for endpoint in tqdm(endpoints):
    df_raw[f'{endpoint}_raw']= extract_supabase_raw(endpoint=endpoint)

 33%|███▎      | 1/3 [00:02<00:04,  2.42s/it]

✅ Extracción correcta realizada para products_raw
Filas: 1198

 67%|██████▋   | 2/3 [00:03<00:01,  1.65s/it]

✅ Extracción correcta realizada para customers_raw
Filas: 1618

100%|██████████| 3/3 [00:05<00:00,  1.71s/it]

✅ Extracción correcta realizada para orders_raw
Filas: 1680

2. Definir funciones de transformacion para cada tabla

In [88]:
df_raw.keys()

dict_keys(['products_raw', 'customers_raw', 'orders_raw'])

**Función TRANSFORM para customers_raw** <p>
Establecer los pasos, hacer pruebas y modularizar.
1. Filtrar columnas no a utilizar

In [93]:
df_raw['customers_raw'].head(2)

,customer.id,customer.email,customer.phone,customer.phone_prefix,customer.status,customer.accepts_marketing,customer.accepted_marketing_at,customer.cancelled_marketing_at,customer.fullname,customer.unconfirmed_email,customer.shipping_addresses,customer.billing_addresses,customer.customer_categories,customer.customer_additional_fields
0,17276830,123franhornig@gmail.com,936993176,+56,approved,False,None,None,Francisca Fuenzalida,None,"[{""name"": ""Francisca"", ""surname"": ""Fuenzalida""...","[{""name"": ""Francisca"", ""surname"": ""Fuenzalida""...",[],"[{""id"": 29701399, ""label"": ""accepts_marketing""..."
1,15462049,2tcloud@jumpseller-mercadolibreapp.com,None,None,approved,False,None,None,Oscar Herrera,None,"[{""name"": ""2TCLOUD"", ""surname"": ""-"", ""address""...","[{""name"": ""oscar"", ""surname"": ""herrera"", ""addr...",[],[]

In [108]:
df_raw['customers_raw']['customer.shipping_addresses'][19] # de aca podemos obtener ubicacion (city, country,municipality )

'[{"name": "ACEMARCHILELTDA", "surname": "-", "address": "Raul Toro 144", "city": "Valpara\\u00edso", "postal": "0000000", "country": "CL", "region": "01", "taxid": "76375827-3", "primary": true, "municipality_code": "8261239", "municipality": "Vi\\u00f1a del Mar"}]'

In [ ]:
# cantidad de categorias con contenido
len(df_raw['customers_raw'][df_raw['customers_raw']['customer.customer_categories']!='[]'])

16

In [124]:
len(df_raw['customers_raw'][df_raw['customers_raw']['customer.shipping_addresses']=='[]' ])

1028

In [97]:
df_raw['customers_raw'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1618 entries, 0 to 1617
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   customer.id                          1618 non-null   int64
 1   customer.email                       1618 non-null   object
 2   customer.phone                       1481 non-null   object
 3   customer.phone_prefix                1405 non-null   object
 4   customer.status                      1618 non-null   object
 5   customer.accepts_marketing           1617 non-null   object
 6   customer.accepted_marketing_at       1140 non-null   object
 7   customer.cancelled_marketing_at      0 non-null      object
 8   customer.fullname                    1618 non-null   object
 9   customer.unconfirmed_email           0 non-null      object
 10  customer.shipping_addresses          1618 non-null   object
 11  customer.billing_addresses           1618 non-null   object
 12  customer.customer_categories         1618 non-null   object
 13  customer.customer_additional_fields  1618 non-null   object
dtypes: int64(1), object(13)
memory usage: 177.1+ KB

In [109]:
df_raw['customers_raw'].isnull().sum()

customer.id                               0
customer.email                            0
customer.phone                          137
customer.phone_prefix                   213
customer.status                           0
customer.accepts_marketing                1
customer.accepted_marketing_at          478
customer.cancelled_marketing_at        1618
customer.fullname                         0
customer.unconfirmed_email             1618
customer.shipping_addresses               0
customer.billing_addresses                0
customer.customer_categories              0
customer.customer_additional_fields       0
dtype: int64

In [126]:
# se eliminan columnas con muchos nulos o irrelevantes para analisis posterior
columnas= df_raw['customers_raw'].columns.to_list()
# columnas a filtrar
columnas_filtro= ['customer.id',
 'customer.status',
 'customer.accepts_marketing',
 'customer.shipping_addresses']

customer_df= df_raw['customers_raw'][columnas_filtro]

Siguiente: 
- Finalizar pasos (funcion) para la parte de Transform de *'customers_raw'*
- Ojo: no demores mucho en analizar, solo dejarlo limpio y normalizado

In [128]:
customer_df

,customer.id,customer.status,customer.accepts_marketing,customer.shipping_addresses
0,17276830,approved,False,"[{""name"": ""Francisca"", ""surname"": ""Fuenzalida""..."
1,15462049,approved,False,"[{""name"": ""2TCLOUD"", ""surname"": ""-"", ""address""..."
2,17506887,approved,False,"[{""name"": ""Julio"", ""surname"": ""Fuenzalida cort..."
3,16776276,approved,True,[]
4,16979494,approved,False,"[{""name"": ""Alexis"", ""surname"": ""Burgos Arcos"",..."
...,...,...,...,...
1613,16776155,approved,True,[]
1614,16775973,approved,True,[]
1615,16775936,approved,True,[]
1616,15934696,approved,False,"[{""name"": ""ZEONEX"", ""surname"": ""-"", ""address"":..."
1617,16776403,approved,True,[]

**Función TRANSFORM para products_raw**

In [92]:
df_raw['products_raw'].head(2)

,product.id,product.name,product.page_title,product.description,product.meta_description,product.price,product.cost_per_item,product.compare_at_price,product.weight,product.stock,...,product.width,product.height,product.diameter,product.google_product_category,product.images,product.variants,product.fields,product.permalink,product.discount,product.currency
0,27766653,Cámara Canon Mirrorless EOS R8 Body,Cámara Canon Mirrorless EOS R8 Body,"<div class=""product-description""><h1>\n ...",Canon EOS R8: Desempeño excepcional y...,1999990,NaN,2499990.0,1.4,1,...,10.0,20.0,0,141,"[{""id"": 57589702, ""url"": ""https://images.jumps...",[],"[{""id"": 13528130, ""custom_field_id"": 68122, ""t...",5803c002aa,0.0,CLP
1,27766654,Cámara Canon Mirrorless EOS R6 MKII Body,Cámara Canon Mirrorless EOS R6 MKII Body,"<div class=""product-description""><h1>Canon EOS...",Canon EOS R6 Mark II: Desempeño multimedia exc...,2989990,NaN,NaN,1.5,1,...,10.0,20.0,0,141,"[{""id"": 57590020, ""url"": ""https://images.jumps...",[],"[{""id"": 13528139, ""custom_field_id"": 68122, ""t...",5666c003aa,0.0,CLP

**Función TRANSFORM para orders_raw**

In [89]:
df_raw['orders_raw'].head(2)

,order.id,order.source.created_from,order.source.created_from_app_code,order.source.source_name,order.source.medium,order.source.campaign,order.source.referral_url,order.source.referral_code,order.source.user_agent,order.source.first_page_visited,...,order.billing_address.region,order.billing_address.country,order.billing_address.country_code,order.billing_address.region_code,order.billing_address.street_number,order.billing_address.complement,order.billing_address.municipality,order.shipping_address,order.shipping_branch,order.customer
0,2679,checkout,None,js-google-shopping-app,js-google-shopping-app,None,https://www.google.com/,None,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://www.kreadores.pro/microfono-inalambric...,...,None,None,None,None,None,None,None,None,None,None
1,2678,checkout,None,revie,revie_star,revie,None,None,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://www.kreadores.pro/ilce-6400l/b,...,Región Metropolitana,Chile,CL,12,None,casa,Vitacura,None,None,None

In [ ]:
# de aca, dejar columna de id de cliente, verificar si coincide len(unique(id)) con los id de la tabla customer
df_raw['orders_raw'].columns

Index(['order.id', 'order.source.created_from',
       'order.source.created_from_app_code', 'order.source.source_name',
       'order.source.medium', 'order.source.campaign',
       'order.source.referral_url', 'order.source.referral_code',
       'order.source.user_agent', 'order.source.first_page_visited',
       'order.source.first_page_visited_at', 'order.source.referral_source',
       'order.created_at', 'order.completed_at', 'order.currency',
       'order.subtotal', 'order.tax', 'order.shipping_tax', 'order.shipping',
       'order.shipping_required', 'order.total', 'order.discount',
       'order.shipping_discount', 'order.gift_cards_discount',
       'order.fulfillment_status', 'order.shipping_method_id',
       'order.shipping_service_id', 'order.shipping_method_name',
       'order.payment_method_name', 'order.payment_method_type',
       'order.payment_information', 'order.payment_notification_id',
       'order.additional_information', 'order.duplicate_url',
       'order.recovery_url', 'order.review_url', 'order.checkout_url',
       'order.coupons', 'order.promotions', 'order.customer.id',
       'order.customer.email', 'order.customer.phone',
       'order.customer.phone_prefix', 'order.customer.ip',
       'order.customer.fullname', 'order.shipping_branch.id',
       'order.shipping_branch.name', 'order.shipping_address.name',
       'order.shipping_address.surname', 'order.shipping_address.address',
       'order.shipping_address.city', 'order.shipping_address.postal',
       'order.shipping_address.region', 'order.shipping_address.country',
       'order.shipping_address.country_code',
       'order.shipping_address.region_code',
       'order.shipping_address.street_number',
       'order.shipping_address.complement', 'order.shipping_address.latitude',
       'order.shipping_address.longitude',
       'order.shipping_address.municipality', 'order.billing_address',
       'order.pickup_address', 'order.products', 'order.additional_fields',
       'order.shipping_taxes', 'order.status', 'order.status_name',
       'order.status_enum', 'order.tracking_url', 'order.tracking_company',
       'order.tracking_number', 'order.shipping_option',
       'order.same_day_delivery', 'order.shipment_status',
       'order.shipment_status_enum', 'order.recovered_from',
       'order.external_shipping_rate_id',
       'order.external_shipping_rate_description', 'order.billing_information',
       'order.billing_address.name', 'order.billing_address.surname',
       'order.billing_address.taxid', 'order.billing_address.address',
       'order.billing_address.city', 'order.billing_address.postal',
       'order.billing_address.region', 'order.billing_address.country',
       'order.billing_address.country_code',
       'order.billing_address.region_code',
       'order.billing_address.street_number',
       'order.billing_address.complement',
       'order.billing_address.municipality', 'order.shipping_address',
       'order.shipping_branch', 'order.customer'],
      dtype='object')

df_raw['orders_raw'].col

In [57]:
df_products['type'].unique()

array(['physical'], dtype=object)

columnas relevantes
- id, name, price, stock, stock_notification, brand, created_at, update_at, categories

In [50]:
df_products.columns

Index(['id', 'name', 'page_title', 'description', 'meta_description', 'price',
       'cost_per_item', 'compare_at_price', 'weight', 'stock',
       'stock_unlimited', 'stock_threshold', 'stock_notification', 'sku',
       'brand', 'barcode', 'featured', 'reviews_enabled', 'status',
       'shipping_required', 'type', 'days_to_expire', 'created_at',
       'updated_at', 'package_format', 'length', 'width', 'height', 'diameter',
       'google_product_category', 'categories', 'images', 'variants', 'fields',
       'permalink', 'discount', 'currency'],
      dtype='object')

In [58]:
columnas_necesarias = ['id', 'name', 'brand', 'price', 'created_at', 'updated_at', 'stock', 'stock_notification', 'categories']
df = df_products[columnas_necesarias].copy()

In [60]:
df.isnull().sum()

id                    0
name                  0
brand                 1
price                 0
created_at            0
updated_at            0
stock                 0
stock_notification    0
categories            0
dtype: int64

In [63]:
type(df['categories'][0])
df_prueba= df.copy()
df_prueba = pd.json_normalize(df['categories'])

In [68]:
df.head(1)

,id,name,brand,price,created_at,updated_at,stock,stock_notification,categories
0,27766653,Cámara Canon Mirrorless EOS R8 Body,Canon,1999990.0,2024-11-23 00:20:22 UTC,2025-08-12 00:47:37 UTC,1,True,"[{'id': 1992493, 'name': 'Video y Fotografía',..."

In [72]:
categorias= df['categories'][0]
lista_categorias= []
for categoria in categorias:
    nombre_cate= categoria['name']
    lista_categorias.append(nombre_cate)

In [73]:
lista_categorias

['Video y Fotografía',
 'Cámaras',
 'Audio',
 'Micrófonos',
 'Marcas',
 'Canon',
 'Micrófono para Vlogging',
 'Cámaras Mirrorless',
 'Cámaras Semiprofesionales',
 'Cámaras para Vlog',
 'Cámaras para Streaming',
 'Cámaras para Youtuber',
 'Cámaras para TikTok',
 'Cámaras para Instagram',
 'Cámaras para Podcast',
 'Cámaras para Grabar Contenido',
 'Cámaras para Transmitir en Vivo',
 'Cámaras para Transmitir en Vivo por Facebook',
 'Cámaras para Viajes',
 'Cámaras para Fotografiar Aves']

In [ ]:
import pandas as pd

def limpiar_y_preparar_productos(df):
    # Renombrar
    df.columns = df.columns.str.replace('^product\.', '', regex=True)

    # Columnas clave
    columnas_necesarias = ['id', 'name', 'brand', 'price', 'created_at', 'updated_at', 'stock', 'stock_notification', 'categories']
    columnas_disponibles = [col for col in columnas_necesarias if col in df.columns]
    df = df[columnas_disponibles].copy()

    # Fechas a datetime
    for fecha_col in ['created_at', 'updated_at']:
        if fecha_col in df.columns:
            df[fecha_col] = pd.to_datetime(df[fecha_col], errors='coerce')
            nulos_fecha = df[fecha_col].isna().sum()
            if nulos_fecha > 0:
                print(f"⚠️ {nulos_fecha} valores nulos en {fecha_col} tras conversión a datetime.")

    # Nulos en texto
    for col in ['name', 'brand']:
        if col in df.columns:
            df[col] = df[col].fillna('No especificado')

    # Nulos en numéricos
    if 'price' in df.columns:
        df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0)

    print("✅ Limpieza y preparación completada.")
    return df

Celular Samusng A55
[{'id': 13528220, 'custom_field_id': 68122, 'type': 'selection', 'label': 'Tamaño del sensor', 'value_id': 137278, 'value': 'APS-C', 'variant_id': None}, {'id': 13528221, 'custom_field_id': 68123, 'type': 'selection', 'label': 'Entrada Micrófono', 'value_id': 137281, 'value': 'Sí', 'variant_id': None}, {'id': 13528222, 'custom_field_id': 68124, 'type': 'selection', 'label': 'Salida de Audífonos', 'value_id': 137282, 'value': 'Sí', 'variant_id': None}, {'id': 13528223, 'custom_field_id': 68125, 'type': 'selection', 'label': 'Megapíxeles', 'value_id': 139859, 'value': '24.2 MP', 'variant_id': None}, {'id': 13528224, 'custom_field_id': 68126, 'type': 'selection', 'label': 'Resolución de Video', 'value_id': 139860, 'value': '4K a 60p', 'variant_id': None}, {'id': 13528225, 'custom_field_id': 68127, 'type': 'selection', 'label': 'Pantalla', 'value_id': 139861, 'value': 'Táctil articulada', 'variant_id': None}, {'id': 13528226, 'custom_field_id': 66671, 'type': 'text', 'label': 'Características', 'value_id': None, 'value': 'Compacta y ligera * Kit ideal para comenzar en la fotografía * Enfoque rápido y preciso * Pantalla táctil vari-angle * Conectividad Wi-Fi y Bluetooth', 'variant_id': None}, {'id': 13528227, 'custom_field_id': 67441, 'type': 'text', 'label': 'Características principales', 'value_id': None, 'value': 'Perfecta para quienes se inician en la fotografía digital. La EOS R100 es compacta y ligera, con un kit completo que incluye una lente versátil, ideal para aprender y capturar momentos con alta calidad.', 'variant_id': None}, {'id': 13528228, 'custom_field_id': 67583, 'type': 'text', 'label': 'include', 'value_id': None, 'value': 'Cámara Canon Mirrorless EOS R100 + Lente RF-S 18-45mm * Batería * Cargador * Cable USB * Correa de cámara * Manual de usuario', 'variant_id': None}, {'id': 13762785, 'custom_field_id': 66692, 'type': 'selection', 'label': 'Seller', 'value_id': 136685, 'value': 'New Line', 'variant_id': None}]